name: BeardAch
main: me.tehbeard.BeardAch.BeardAch
version: 0.2
depend: [Permissions,BeardStat]
softdepend: [DroxPerms]
commands:
    ach:
        description: Show your achievements
        usage: /<command>
