name: BeardAch
main: me.tehbeard.BeardAch.BeardAch
version: ${project.plugin.version}
softdepend: [WorldGuard,DroxPerms,Vault,BeardStat] 
commands:
    ach:
        description: Show your achievements
        usage: /<command>
    ach-reload:
        description: reloads the achievements
        usage: /<command>
    ach-fancy:
        description: dumps achievement definitions to database
        usage: |
            /<command> - Show latest achievements unlocked
            /<command> -n 2 - Show second page of achievements unlocked
            /<command> -p herpderp - Show herpderp's achievements
            /<command> -p herpderp -n 3 - show 3rd page of herpderp's achievements
            /<command> -a 5 - Show achievement number 5
permissions:
  beardach.reload:
    description: Allows you to reload the achievements list
    default: op
    children:
      beardach.reload.fancy: true
  beardach.reload.fancy:
    description: allows you to use /ach-fancy to make external ach displays
    default: false
