name: BeardAch
main: me.tehbeard.BeardAch.BeardAch
version: ${project.plugin.version}
depend: [BeardStat]
softdepend: [DroxPerms,worldguard,Vault] 
commands:
    ach:
        description: Show your achievements
        usage: /<command>
    ach-reload:
        description: reloads the achievements
        usage: /<command>
    ach-fancy:
        description: Use to update any output displays slug->fancy DB
        usage: /<command>
permissions:
  beardach.reload:
    description: Allows you to reload the achievements list
    default: op
    children:
      beardach.reload.fancy: true
  beardach.reload.fancy:
    description: allows you to use /ach-fancy to make external ach displays
    default: false
