name: BeardAch
main: me.tehbeard.BeardAch.BeardAch
version: {VERSION}
depend: [BeardStat]
softdepend: [DroxPerms,worldguard]
commands:
    ach:
        description: Show your achievements
        usage: /<command>
    ach-reload:
        description: reloads the achievements
        usage: /<command>
    ach-fancy:
        description: Use to update any output displays slug->fancy DB
        usage: /<command>
        